"""Genera (o regenera) los metadatos de los 30 módulos en src/content/modules/*.yaml.

Fuente: PLAN.md §7.1. Los módulos con lecciones ya escritas se conservan tal cual
(no se sobrescribe un YAML existente). Uso: python scripts/gen-modules.py
"""

from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parents[1] / "src" / "content" / "modules"

PARTS = {
    0: "Parte 0 · Fundamentos del oficio",
    1: "Parte I · Herramientas núcleo",
    2: "Parte II · Visualización y comunicación",
    3: "Parte III · Estadística, experimentación y causalidad",
    4: "Parte IV · Analítica por dominio",
    5: "Parte V · Stack moderno e ingeniería analítica",
    6: "Parte VI · IA para analistas",
    7: "Parte VII · Carrera profesional",
}

# (id, parte, orden, título, descripción, [objetivos], horas, volatilidad)
MODULES = [
    ("analista-2026", 0, 0, "El data analyst en 2026",
     "Qué hace un analista hoy, cómo ha cambiado el rol con la IA y el ciclo del análisis de la pregunta a la decisión.",
     ["Distinguir los perfiles de datos (analista, analytics engineer, data scientist, data engineer).",
      "Aplicar el ciclo pregunta-datos-análisis-decisión-seguimiento a un caso real.",
      "Describir el stack moderno y el papel de la IA y la capa semántica en el trabajo del analista."], 4, "medium"),
    ("pensamiento-negocio", 0, 1, "Pensamiento analítico y de negocio",
     "Formular la pregunta correcta, descomponer problemas, definir métricas sin ambigüedad y entender la economía de una empresa.",
     ["Descomponer un problema de negocio con un árbol de hipótesis (MECE).",
      "Diseñar un árbol de KPIs con métrica estrella, métricas de entrada y métricas de control (guardrails).",
      "Definir una métrica con grano, filtros, ventana y numerador/denominador explícitos."], 6, "low"),
    ("estadistica-descriptiva", 0, 2, "Estadística descriptiva y probabilidad",
     "Tipos de variables, distribuciones, medidas de centralidad y dispersión, probabilidad condicional y el teorema central del límite.",
     ["Elegir entre media, mediana y percentiles según la distribución.",
      "Aplicar la probabilidad condicional y el teorema de Bayes a un problema de negocio.",
      "Explicar el teorema central del límite y por qué importa para la inferencia."], 8, "low"),
    ("hojas-de-calculo", 1, 3, "Hojas de cálculo modernas",
     "Excel y Google Sheets con funciones dinámicas, Power Query, modelado y asistentes de IA, con nombres de función en español e inglés.",
     ["Usar matrices dinámicas, LET y LAMBDA para sustituir fórmulas frágiles.",
      "Limpiar y transformar datos con Power Query y modelar con tablas dinámicas.",
      "Auditar un libro y verificar el trabajo de un asistente de IA dentro de la hoja."], 10, "high"),
    ("sql-ii", 1, 5, "SQL II — Analítico avanzado",
     "CTEs, funciones de ventana, QUALIFY, pivotado, fechas y patrones de análisis (cohortes, sesiones, rachas).",
     ["Resolver rankings, acumulados y comparaciones con funciones de ventana.",
      "Construir tablas de cohortes, funnels y sesionización en SQL.",
      "Escribir SQL legible con CTEs y trasladarlo entre dialectos."], 12, "low"),
    ("sql-iii", 1, 6, "SQL III — Rendimiento y modelado de datos",
     "Almacenamiento columnar, planes de ejecución, coste en warehouses y modelado dimensional.",
     ["Leer un plan de ejecución y reducir el coste de una consulta.",
      "Diseñar un esquema en estrella con el grano correcto.",
      "Aplicar convenciones de estilo SQL y la arquitectura medallón."], 8, "low"),
    ("python-analisis", 1, 7, "Python para análisis",
     "pandas 3, Polars, DuckDB desde Python, notebooks reproducibles y cuándo usar cada herramienta.",
     ["Manipular datos con pandas 3 y entender Copy-on-Write y el dtype str.",
      "Escribir transformaciones equivalentes en Polars (lazy) y DuckDB.",
      "Montar un análisis reproducible en un notebook."], 12, "high"),
    ("limpieza-calidad", 1, 8, "Limpieza y calidad de datos",
     "Datos ordenados, valores ausentes, outliers, duplicados, validación y contratos de datos.",
     ["Diagnosticar problemas de calidad con un perfilado sistemático.",
      "Elegir una estrategia para valores ausentes según su mecanismo.",
      "Automatizar validaciones y documentar los supuestos."], 8, "medium"),
    ("eda", 1, 9, "Análisis exploratorio (EDA)",
     "Explorar con preguntas, no con gráficos al azar: segmentación, paradoja de Simpson, sesgos y checklist reproducible.",
     ["Plantear preguntas antes de graficar y recorrer un EDA de forma sistemática.",
      "Reconocer la paradoja de Simpson y los sesgos de selección y supervivencia.",
      "Documentar hallazgos de forma reproducible."], 8, "low"),
    ("visualizacion", 2, 10, "Visualización de datos",
     "Percepción, elección de gráfico, color accesible, gramática de gráficos y cómo mienten los gráficos.",
     ["Elegir el gráfico adecuado para cada pregunta.",
      "Aplicar color, anotaciones y títulos que comunican la conclusión.",
      "Detectar y corregir gráficos engañosos."], 8, "medium"),
    ("dashboards-bi", 2, 11, "Dashboards y BI",
     "Diseño de dashboards, Power BI y DAX, Tableau, Looker y BI como código.",
     ["Diseñar un dashboard con jerarquía, contexto y comparación.",
      "Modelar en estrella y escribir medidas DAX con contexto de filtro.",
      "Elegir una herramienta de BI según el caso."], 14, "high"),
    ("storytelling", 2, 12, "Storytelling y comunicación",
     "Estructurar mensajes con el principio de la pirámide, comunicar incertidumbre y gestionar stakeholders.",
     ["Estructurar un resumen ejecutivo con la recomendación primero.",
      "Comunicar incertidumbre y límites sin diluir el mensaje.",
      "Priorizar peticiones y gestionar expectativas de stakeholders."], 6, "low"),
    ("inferencia", 3, 13, "Inferencia estadística",
     "Muestreo, intervalos de confianza, bootstrap, contrastes de hipótesis, potencia y comparaciones múltiples.",
     ["Interpretar correctamente un p-valor y un intervalo de confianza.",
      "Calcular potencia y tamaño de muestra.",
      "Controlar comparaciones múltiples."], 12, "low"),
    ("experimentacion", 3, 14, "Experimentación y A/B testing",
     "Diseño, potencia, SRM, CUPED, tests secuenciales, métricas de ratio y cultura de experimentación.",
     ["Diseñar un experimento con métrica primaria, guardrails y potencia.",
      "Detectar un SRM y reducir varianza con CUPED.",
      "Evitar el peeking con métodos secuenciales."], 14, "medium"),
    ("causalidad", 3, 15, "Inferencia causal sin experimentos",
     "DAGs, diferencias en diferencias, control sintético, regresión discontinua y emparejamiento.",
     ["Dibujar un DAG e identificar confusores, colisionadores y mediadores.",
      "Estimar un efecto con diferencias en diferencias y comprobar tendencias paralelas.",
      "Decidir cuándo basta un análisis observacional."], 14, "low"),
    ("regresion-modelos", 3, 16, "Regresión y modelos para analistas",
     "Regresión lineal y logística interpretadas para negocio, validación, interpretabilidad y segmentación.",
     ["Interpretar coeficientes de una regresión para negocio.",
      "Validar un modelo y evitar la fuga de información.",
      "Segmentar clientes (RFM, k-means) conociendo sus trampas."], 12, "low"),
    ("series-temporales", 3, 17, "Series temporales y forecasting",
     "Estacionalidad, descomposición, modelos clásicos y fundacionales, backtesting y detección de anomalías.",
     ["Descomponer una serie y elegir un modelo de referencia.",
      "Evaluar un pronóstico con backtesting de origen móvil.",
      "Comparar honestamente modelos clásicos y fundacionales."], 12, "high"),
    ("analitica-producto", 4, 18, "Analítica de producto",
     "Eventos, funnels, retención, cohortes y diagnóstico de caídas de métricas.",
     ["Diseñar un plan de tracking.",
      "Construir y leer curvas de retención y growth accounting.",
      "Seguir un checklist para investigar una caída de métrica."], 10, "medium"),
    ("marketing-clientes", 4, 19, "Analítica de marketing y clientes",
     "Atribución, incrementalidad, Marketing Mix Modeling, valor de cliente y churn.",
     ["Distinguir atribución de incrementalidad.",
      "Calcular valor de cliente y churn.",
      "Interpretar un modelo de marketing mix con sus límites."], 10, "high"),
    ("finanzas-operaciones", 4, 20, "Analítica financiera y de operaciones",
     "Unit economics, métricas SaaS, análisis de varianzas, inventario y pricing.",
     ["Calcular y leer unit economics y métricas de suscripción.",
      "Descomponer una varianza en precio, volumen y mix.",
      "Analizar rotación de inventario y roturas de stock."], 10, "low"),
    ("stack-moderno", 5, 21, "El stack de datos moderno",
     "Warehouses y lakehouses, formatos de tabla abiertos, ELT, orquestación y analítica local-first.",
     ["Situar cada herramienta del stack en el flujo de datos.",
      "Comparar warehouse, lakehouse y analítica local.",
      "Entender formatos abiertos como Iceberg y Delta."], 8, "high"),
    ("ingenieria-analitica", 5, 22, "Ingeniería analítica con dbt",
     "Modelos, tests, documentación, incrementales, CI para datos y el nuevo motor Fusion.",
     ["Estructurar un proyecto dbt en capas.",
      "Escribir tests y contratos de datos.",
      "Revisar y desplegar cambios de SQL con CI."], 12, "high"),
    ("capa-semantica", 5, 23, "Capa semántica y métricas",
     "Definir métricas una vez: MetricFlow, OSI, LookML, modelos semánticos y su papel en la analítica con IA.",
     ["Definir entidades, dimensiones y métricas como código.",
      "Explicar por qué la capa semántica es requisito de la analítica con IA.",
      "Gobernar definiciones de métricas."], 8, "high"),
    ("gobierno-etica", 5, 24, "Gobierno, privacidad y ética",
     "RGPD, anonimización, control de acceso, AI Act y ética de los datos y los experimentos.",
     ["Aplicar minimización de datos y base legal en un análisis.",
      "Distinguir anonimización de seudonimización.",
      "Identificar riesgos éticos y de sesgo en una métrica."], 6, "high"),
    ("llm-copiloto", 6, 25, "LLMs como copiloto del analista",
     "Usar LLMs y agentes de código para analizar más rápido sin perder rigor: contexto, verificación y límites.",
     ["Dar contexto y definiciones a un LLM para obtener análisis útiles.",
      "Aplicar un protocolo de verificación a resultados generados.",
      "Saber qué datos no se deben compartir con un modelo."], 8, "high"),
    ("text-to-sql", 6, 26, "Text-to-SQL y analítica conversacional",
     "Cómo funciona, por qué falla, qué aporta la capa semántica y cómo evaluarlo con un golden set.",
     ["Explicar los modos de fallo del text-to-SQL.",
      "Construir un golden set de preguntas y resultados esperados.",
      "Valorar productos de analítica conversacional."], 8, "high"),
    ("analitica-agentica-mcp", 6, 27, "Analítica agéntica y MCP",
     "Agentes y MCP sobre datos: diseño seguro, evaluación de conclusiones y límites.",
     ["Diferenciar workflows y agentes.",
      "Diseñar un servidor MCP de datos de solo lectura y con límites de coste.",
      "Evaluar las conclusiones de un agente."], 8, "high"),
    ("llm-texto", 6, 28, "LLMs para datos no estructurados",
     "Clasificación y extracción sobre texto, funciones de IA en SQL, embeddings y evaluación contra etiquetas.",
     ["Clasificar y extraer información de texto con salidas estructuradas.",
      "Evaluar un clasificador contra etiquetas humanas.",
      "Estimar coste y diseñar el muestreo."], 8, "high"),
    ("carrera-entrevistas", 7, 29, "Portfolio, carrera y entrevistas",
     "Qué buscan las empresas, portfolio, entrevistas de SQL, producto y estadística, certificaciones y primeros 90 días.",
     ["Construir un portfolio con tres casos completos.",
      "Preparar entrevistas de SQL, métricas y estadística.",
      "Planificar los primeros 90 días en un equipo de datos."], 8, "medium"),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    created = 0
    for mid, part, order, title, desc, objectives, hours, vol in MODULES:
        path = OUT / f"{mid}.yaml"
        if path.exists():
            continue
        data = {
            "id": mid,
            "part": PARTS[part],
            "partOrder": part,
            "order": order,
            "title": title,
            "description": desc,
            "objectives": objectives,
            "estimatedHours": hours,
            "volatility": vol,
        }
        path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=100), encoding="utf-8")
        created += 1
    print(f"{created} módulos creados; {len(MODULES)} definidos en total.")


if __name__ == "__main__":
    main()
